### ISSUE TITLE
Monthly Masters 

### ISSUE THREAD

**Issue by banillie** [yulqen/datamaps#17]
Hi @yulqen is it possible for datamaps Master classes to record the month for data. e.g. Jan 2021. This would be useful in addition to quarters. Thanks.

**Comment by yulqen** [comment]
Sure - could do that. What is the requirement for the month attribute - the first month of the quarter?  Do you need it as a `date` object or text and if so - what format? We can discuss.

**Comment by banillie** [comment]
This would be something separate to quarters. So you have the ability to specify a month (from a possible 12) and a year. 
I'm asking because we are going to start using DMs for a quarterly reporting process. 
Cheers.

**Comment by yulqen** [comment]
Sorry to labour the point,  but would you be able to provide an example - in code - of what you would like to see?

At present, you create a `Master` using something like:

`m = project_data_from_master("master.xlsx", 1, 2021)`

This results in an object: `Master()` object whose attributes you can query with, for example:

    * `quarter = m.quarter`
    * `data = m.data`
    * 'year = m.year`

Additionally, the `quarter` object here can then be queried for its financial year properties, e.g.:

`fy = quarter.fy`

whose properties are:

`fy.q1` (results in "2021-04-01", for example)
    
You mention you want to be able to specify a month, so is it as simple as creating the month with the following?

    * `m = project_data_from_master("master.xlsx", 7, 2021)` (for July, for example)

And therefore, what do you need out of the resulting object?

    * `month = m.month`

The obvious attributes are `m.start_date`, `m.end_date`, `m.long_name` ("January"), `m.short_name` ("Jan") - etc.

Let me know if I'm on the right track.

**Comment by banillie** [comment]
Yes it is a simple as creating a month e.g. `project_data_from_master("master.xlsx", 7, 2021)` (for July, for example)` as above. 

The `Master()` object would then have the following attributes. 

```
quarter = m.quarter
data = m.data
year = m.year
month = m.month
```

From a user case perspective you'd need to specify a month or quarter. No need for both. The reason for this is, is it allows for quarter or monthly reporting cycles.

**Comment by yulqen** [comment]
I'm finishing up the work on this - to be released in a new version of
datamaps this week.

There is a new function you will need to import:
`datamaps.api.project_data_from_master_month`. It is somewhat
troublesome to try to use the current function for this
(`project_data_from_master`) - the reason is related to the function
signature and the unnecessary complexity of trying to detect whether the
caller is passing in a month or a quarter. Example, in the current API:

```python
from datamaps.api import project_data_from_master

d = project_data_from_master("master.xlsx", 3, 2021)
assert d.quarter== 3
```

The signature of this function is `project_data_from_master(master,
quarter, year)`. It would be nice to be able to use the same function
and instead of passing in a quarter integer here, pass in a month
integer, e.g. `project_data_from_master("master.xlsx", 12,
2021)` but that exposes a little too much instability - you have to test
whether the caller means a quarter or a month here and opens up a bunch
of problems.

Instead, the new func added to the API goes like this:

```python
from datamaps.api import project_data_from_master_month

d = project_data_from_master_month("master.xlsx", 10, 2021)
assert d.quarter==Quarter(3, 2021)
assert d.month.name == "October"
assert d.month.start_date == datetime.date(2021, 10, 1)
assert d.month.end_date == datatime.date(2021, 10, 31)
assert d.quarter.months==[Month(October), Month(November),
Month(December)]
```

I just need to fix a few bits related to leap years. This will be coming
out in datamaps `v1.1.6`.

**Comment by banillie** [comment]
@yulqen thanks very much for this. I think this arrangement will work nicely. Having two different functions is not a problem. Cheers.

**Comment by yulqen** [comment]
Implemented in `v1.1.6` - now released on PyPI. Update with `pip install
-U datamaps`.

Use:

`from datamaps.api import project_data_from_master_month`.

Report bugs!

**Comment by yulqen** [comment]
Updated to `v1.1.7` to fix bug in `repr()`.

**Comment by banillie** [comment]
Hiya @yulqen sorry only just getting to this now, but going to try it out. cheers.

**Comment by banillie** [comment]
@yulqen I was able to integrate this into analysis_engine now problem. One of the reporting process now uses monthly masters.
